export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_VALIDATION_ERROR = "RESET_PASSWORD_REQUEST_VALIDATION_ERROR";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_FAILURE = "RESET_PASSWORD_REQUEST_FAILURE";

export function requestResetPassword(payload) {
  return {
    type: RESET_PASSWORD_REQUEST,
    payload,
  };
}
